name: "Issue Scouter"
description: "Github action to list of issues you can contribute"
branding:
  icon: "search"
  color: "blue"
inputs:
  config_file:
    description: "YAML configuration file"
    required: true
  dry_run:
    description: "Run without committing and pushing changes"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
